version: "3"

services:
  dynamodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - strategic:/home/dynamodblocal/db

volumes:
  strategic:
    driver: local
